defmodule Nadia.Behaviour do
  alias Nadia.Client

  alias Nadia.Model.{
    BotAccessSettings,
    BotCommand,
    BotDescription,
    BotName,
    BotShortDescription,
    BusinessConnection,
    Chat,
    ChatAdministratorRights,
    ChatInviteLink,
    ChatMember,
    Error,
    File,
    ForumTopic,
    GameHighScore,
    Gifts,
    MenuButton,
    Message,
    MessageId,
    OwnedGifts,
    Poll,
    PreparedInlineMessage,
    PreparedKeyboardButton,
    SentGuestMessage,
    SentWebAppMessage,
    StarAmount,
    StarTransactions,
    Story,
    Sticker,
    Update,
    User,
    UserChatBoosts,
    UserProfileAudios,
    UserProfilePhotos,
    WebhookInfo
  }

  use Nadia.Behaviour.BotAccount
  use Nadia.Behaviour.GiftsAndVerification
  use Nadia.Behaviour.Messages
  use Nadia.Behaviour.Games
  use Nadia.Behaviour.UpdatesAndFiles
  use Nadia.Behaviour.Chats
  use Nadia.Behaviour.Business
  use Nadia.Behaviour.Payments
  use Nadia.Behaviour.ManagedBots
  use Nadia.Behaviour.Interactions
  use Nadia.Behaviour.Stickers
  use Nadia.Behaviour.PinnedMessages

  @optional_callbacks get_me: 1,
                      log_out: 0,
                      log_out: 1,
                      close: 0,
                      close: 1,
                      set_my_commands: 1,
                      set_my_commands: 2,
                      set_my_commands: 3,
                      delete_my_commands: 0,
                      delete_my_commands: 1,
                      delete_my_commands: 2,
                      get_my_commands: 0,
                      get_my_commands: 1,
                      get_my_commands: 2,
                      set_my_name: 0,
                      set_my_name: 1,
                      set_my_name: 2,
                      get_my_name: 0,
                      get_my_name: 1,
                      get_my_name: 2,
                      set_my_description: 0,
                      set_my_description: 1,
                      set_my_description: 2,
                      get_my_description: 0,
                      get_my_description: 1,
                      get_my_description: 2,
                      set_my_short_description: 0,
                      set_my_short_description: 1,
                      set_my_short_description: 2,
                      get_my_short_description: 0,
                      get_my_short_description: 1,
                      get_my_short_description: 2,
                      set_my_profile_photo: 1,
                      set_my_profile_photo: 2,
                      remove_my_profile_photo: 0,
                      remove_my_profile_photo: 1,
                      remove_my_profile_photo: 2,
                      set_chat_menu_button: 0,
                      set_chat_menu_button: 1,
                      set_chat_menu_button: 2,
                      get_chat_menu_button: 0,
                      get_chat_menu_button: 1,
                      get_chat_menu_button: 2,
                      set_my_default_administrator_rights: 0,
                      set_my_default_administrator_rights: 1,
                      set_my_default_administrator_rights: 2,
                      get_my_default_administrator_rights: 0,
                      get_my_default_administrator_rights: 1,
                      get_my_default_administrator_rights: 2,
                      set_user_emoji_status: 1,
                      set_user_emoji_status: 2,
                      set_user_emoji_status: 3,
                      get_available_gifts: 0,
                      get_available_gifts: 1,
                      get_user_gifts: 1,
                      get_user_gifts: 2,
                      get_user_gifts: 3,
                      get_chat_gifts: 1,
                      get_chat_gifts: 2,
                      get_chat_gifts: 3,
                      send_gift: 1,
                      send_gift: 2,
                      send_gift: 3,
                      gift_premium_subscription: 3,
                      gift_premium_subscription: 4,
                      gift_premium_subscription: 5,
                      verify_user: 1,
                      verify_user: 2,
                      verify_user: 3,
                      verify_chat: 1,
                      verify_chat: 2,
                      verify_chat: 3,
                      remove_user_verification: 1,
                      remove_user_verification: 2,
                      remove_chat_verification: 1,
                      remove_chat_verification: 2,
                      send_message: 4,
                      send_rich_message: 2,
                      send_rich_message: 3,
                      send_rich_message: 4,
                      forward_message: 4,
                      forward_message: 5,
                      forward_messages: 4,
                      forward_messages: 5,
                      copy_message: 4,
                      copy_message: 5,
                      copy_messages: 4,
                      copy_messages: 5,
                      send_photo: 4,
                      send_audio: 4,
                      send_document: 4,
                      send_sticker: 4,
                      send_video: 4,
                      send_voice: 4,
                      send_video_note: 4,
                      send_live_photo: 5,
                      send_media_group: 4,
                      send_paid_media: 5,
                      send_poll: 4,
                      send_dice: 2,
                      send_dice: 3,
                      send_game: 2,
                      send_game: 3,
                      send_game: 4,
                      send_checklist: 4,
                      send_checklist: 5,
                      send_message_draft: 3,
                      send_message_draft: 4,
                      send_rich_message_draft: 3,
                      send_rich_message_draft: 4,
                      send_rich_message_draft: 5,
                      send_animation: 4,
                      send_location: 5,
                      send_venue: 7,
                      send_contact: 5,
                      send_chat_action: 3,
                      send_chat_action: 4,
                      get_user_profile_photos: 3,
                      get_user_profile_audios: 1,
                      get_user_profile_audios: 2,
                      get_user_profile_audios: 3,
                      set_game_score: 2,
                      set_game_score: 3,
                      set_game_score: 4,
                      get_game_high_scores: 1,
                      get_game_high_scores: 2,
                      get_game_high_scores: 3,
                      get_updates: 2,
                      set_webhook: 2,
                      delete_webhook: 1,
                      delete_webhook: 2,
                      get_webhook_info: 1,
                      get_file: 2,
                      get_file_link: 2,
                      ban_chat_member: 3,
                      leave_chat: 2,
                      unban_chat_member: 3,
                      unban_chat_member: 4,
                      restrict_chat_member: 4,
                      restrict_chat_member: 5,
                      promote_chat_member: 3,
                      promote_chat_member: 4,
                      set_chat_administrator_custom_title: 4,
                      set_chat_member_tag: 3,
                      set_chat_member_tag: 4,
                      ban_chat_sender_chat: 3,
                      unban_chat_sender_chat: 3,
                      set_chat_permissions: 3,
                      set_chat_permissions: 4,
                      approve_chat_join_request: 3,
                      decline_chat_join_request: 3,
                      delete_chat_photo: 2,
                      set_chat_photo: 2,
                      set_chat_photo: 3,
                      set_chat_title: 3,
                      set_chat_description: 2,
                      set_chat_description: 3,
                      unpin_all_chat_messages: 2,
                      set_chat_sticker_set: 3,
                      delete_chat_sticker_set: 2,
                      get_forum_topic_icon_stickers: 1,
                      create_forum_topic: 3,
                      create_forum_topic: 4,
                      edit_forum_topic: 3,
                      edit_forum_topic: 4,
                      close_forum_topic: 3,
                      reopen_forum_topic: 3,
                      delete_forum_topic: 3,
                      unpin_all_forum_topic_messages: 3,
                      edit_general_forum_topic: 3,
                      close_general_forum_topic: 2,
                      reopen_general_forum_topic: 2,
                      hide_general_forum_topic: 2,
                      unhide_general_forum_topic: 2,
                      unpin_all_general_forum_topic_messages: 2,
                      get_chat: 2,
                      export_chat_invite_link: 1,
                      export_chat_invite_link: 2,
                      create_chat_invite_link: 1,
                      create_chat_invite_link: 2,
                      create_chat_invite_link: 3,
                      edit_chat_invite_link: 2,
                      edit_chat_invite_link: 3,
                      edit_chat_invite_link: 4,
                      create_chat_subscription_invite_link: 3,
                      create_chat_subscription_invite_link: 4,
                      create_chat_subscription_invite_link: 5,
                      edit_chat_subscription_invite_link: 2,
                      edit_chat_subscription_invite_link: 3,
                      edit_chat_subscription_invite_link: 4,
                      revoke_chat_invite_link: 2,
                      revoke_chat_invite_link: 3,
                      get_chat_administrators: 2,
                      get_chat_administrators: 3,
                      get_chat_member_count: 2,
                      get_chat_member: 3,
                      get_user_chat_boosts: 3,
                      get_business_connection: 2,
                      get_business_account_star_balance: 1,
                      get_business_account_star_balance: 2,
                      get_business_account_gifts: 1,
                      get_business_account_gifts: 2,
                      get_business_account_gifts: 3,
                      read_business_message: 3,
                      read_business_message: 4,
                      delete_business_messages: 2,
                      delete_business_messages: 3,
                      set_business_account_name: 2,
                      set_business_account_name: 3,
                      set_business_account_name: 4,
                      set_business_account_username: 1,
                      set_business_account_username: 2,
                      set_business_account_username: 3,
                      set_business_account_bio: 1,
                      set_business_account_bio: 2,
                      set_business_account_bio: 3,
                      set_business_account_profile_photo: 2,
                      set_business_account_profile_photo: 3,
                      set_business_account_profile_photo: 4,
                      remove_business_account_profile_photo: 1,
                      remove_business_account_profile_photo: 2,
                      remove_business_account_profile_photo: 3,
                      set_business_account_gift_settings: 3,
                      set_business_account_gift_settings: 4,
                      transfer_business_account_stars: 2,
                      transfer_business_account_stars: 3,
                      convert_gift_to_stars: 2,
                      convert_gift_to_stars: 3,
                      upgrade_gift: 2,
                      upgrade_gift: 3,
                      upgrade_gift: 4,
                      transfer_gift: 3,
                      transfer_gift: 4,
                      transfer_gift: 5,
                      post_story: 3,
                      post_story: 4,
                      post_story: 5,
                      edit_story: 3,
                      edit_story: 4,
                      edit_story: 5,
                      delete_story: 2,
                      delete_story: 3,
                      repost_story: 4,
                      repost_story: 5,
                      repost_story: 6,
                      send_invoice: 6,
                      send_invoice: 7,
                      send_invoice: 8,
                      create_invoice_link: 5,
                      create_invoice_link: 6,
                      create_invoice_link: 7,
                      answer_shipping_query: 2,
                      answer_shipping_query: 3,
                      answer_shipping_query: 4,
                      answer_pre_checkout_query: 2,
                      answer_pre_checkout_query: 3,
                      answer_pre_checkout_query: 4,
                      get_my_star_balance: 0,
                      get_my_star_balance: 1,
                      get_star_transactions: 0,
                      get_star_transactions: 1,
                      get_star_transactions: 2,
                      refund_star_payment: 2,
                      refund_star_payment: 3,
                      edit_user_star_subscription: 3,
                      edit_user_star_subscription: 4,
                      get_managed_bot_token: 2,
                      replace_managed_bot_token: 2,
                      get_managed_bot_access_settings: 2,
                      set_managed_bot_access_settings: 4,
                      get_user_personal_chat_messages: 3,
                      answer_chat_join_request_query: 2,
                      answer_chat_join_request_query: 3,
                      send_chat_join_request_web_app: 2,
                      send_chat_join_request_web_app: 3,
                      delete_messages: 3,
                      delete_message_reaction: 4,
                      delete_all_message_reactions: 3,
                      set_message_reaction: 4,
                      answer_callback_query: 3,
                      answer_guest_query: 4,
                      answer_web_app_query: 2,
                      answer_web_app_query: 3,
                      save_prepared_inline_message: 2,
                      save_prepared_inline_message: 3,
                      save_prepared_inline_message: 4,
                      save_prepared_keyboard_button: 2,
                      save_prepared_keyboard_button: 3,
                      edit_message_text: 6,
                      edit_message_caption: 5,
                      edit_message_reply_markup: 5,
                      edit_message_media: 2,
                      edit_message_media: 3,
                      edit_message_live_location: 4,
                      stop_message_live_location: 2,
                      edit_message_checklist: 5,
                      edit_message_checklist: 6,
                      stop_poll: 3,
                      stop_poll: 4,
                      set_passport_data_errors: 2,
                      set_passport_data_errors: 3,
                      approve_suggested_post: 3,
                      approve_suggested_post: 4,
                      decline_suggested_post: 3,
                      decline_suggested_post: 4,
                      answer_inline_query: 4,
                      get_sticker_set: 2,
                      get_custom_emoji_stickers: 1,
                      get_custom_emoji_stickers: 2,
                      upload_sticker_file: 3,
                      create_new_sticker_set: 7,
                      add_sticker_to_set: 6,
                      replace_sticker_in_set: 4,
                      replace_sticker_in_set: 5,
                      set_sticker_emoji_list: 2,
                      set_sticker_emoji_list: 3,
                      set_sticker_keywords: 1,
                      set_sticker_keywords: 2,
                      set_sticker_keywords: 3,
                      set_sticker_mask_position: 1,
                      set_sticker_mask_position: 2,
                      set_sticker_mask_position: 3,
                      set_sticker_set_title: 2,
                      set_sticker_set_title: 3,
                      set_sticker_set_thumbnail: 2,
                      set_sticker_set_thumbnail: 3,
                      set_sticker_set_thumbnail: 4,
                      set_custom_emoji_sticker_set_thumbnail: 1,
                      set_custom_emoji_sticker_set_thumbnail: 2,
                      set_custom_emoji_sticker_set_thumbnail: 3,
                      set_sticker_position_in_set: 3,
                      delete_sticker_from_set: 2,
                      delete_sticker_set: 1,
                      delete_sticker_set: 2,
                      pin_chat_message: 4,
                      unpin_chat_message: 2,
                      unpin_chat_message: 3
end
